<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="empcss.css"?>
<!-- <?xml-stylesheet type="text/xsl" href="lab3.xsl"?> -->
 
    
<!-- <!DOCTYPE employees [ 
<!ELEMENT employees (employee+)>
<!ATTLIST employee gender CDATA #REQUIRED>
<!ELEMENT employee (name,phones,addresses,email)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type ( home | work | mobile) "mobile">
<!ELEMENT addresses (address+)>
<!ELEMENT address (street,building,Number,Region,city,Country)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT street (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
]> -->
<employees>
   <employee>
        
    <name >Adham</name>
    <phone>0123456789</phone>
    <address>11 street xyz</address>
    <email>mustexist@gmail.com</email>

   </employee>

   <employee>
        
    <name >Amal</name>
    <phone>0198456789</phone>
    <address>12 street xyz</address>
    <email>asdexist@gmail.com</email>

   </employee>

   <employee>
        
    <name >Ahmed</name>
    <phone>0154456789</phone>
    <address>13 street xyz</address>
    <email>blaexist@gmail.com</email>

   </employee>

</employees>